name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Auto-Merge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.PAT_TOKEN }}  # Ensure this token has the required permissions
